
package gs.nom.mx.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IwsValida", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IwsValida {


    /**
     * 
     * @param nombreDocumento
     * @param identificador
     * @param constanciaBase64
     * @param password
     * @param usuarioProveedor
     * @param documentoBase64
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NOM2002", action = "http://tempuri.org/IwsValida/NOM2002")
    @WebResult(name = "NOM2002Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NOM2002", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.NOM2002")
    @ResponseWrapper(localName = "NOM2002Response", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.NOM2002Response")
    public String nom2002(
        @WebParam(name = "usuarioProveedor", targetNamespace = "http://tempuri.org/")
        String usuarioProveedor,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "identificador", targetNamespace = "http://tempuri.org/")
        String identificador,
        @WebParam(name = "constanciaBase64", targetNamespace = "http://tempuri.org/")
        String constanciaBase64,
        @WebParam(name = "documentoBase64", targetNamespace = "http://tempuri.org/")
        String documentoBase64,
        @WebParam(name = "nombreDocumento", targetNamespace = "http://tempuri.org/")
        String nombreDocumento);

    /**
     * 
     * @param nombreDocumento
     * @param identificador
     * @param constanciaBase64
     * @param password
     * @param usuarioProveedor
     * @param documentoBase64
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NOM2016", action = "http://tempuri.org/IwsValida/NOM2016")
    @WebResult(name = "NOM2016Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NOM2016", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.NOM2016")
    @ResponseWrapper(localName = "NOM2016Response", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.NOM2016Response")
    public String nom2016(
        @WebParam(name = "usuarioProveedor", targetNamespace = "http://tempuri.org/")
        String usuarioProveedor,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "identificador", targetNamespace = "http://tempuri.org/")
        String identificador,
        @WebParam(name = "constanciaBase64", targetNamespace = "http://tempuri.org/")
        String constanciaBase64,
        @WebParam(name = "documentoBase64", targetNamespace = "http://tempuri.org/")
        String documentoBase64,
        @WebParam(name = "nombreDocumento", targetNamespace = "http://tempuri.org/")
        String nombreDocumento);

    /**
     * 
     * @param identificador
     * @param tsBase64
     * @param password
     * @param usuarioProveedor
     * @param documentoBase64
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TS", action = "http://tempuri.org/IwsValida/TS")
    @WebResult(name = "TSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TS", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.TS")
    @ResponseWrapper(localName = "TSResponse", targetNamespace = "http://tempuri.org/", className = "gs.nom.mx.ws.TSResponse")
    public String ts(
        @WebParam(name = "usuarioProveedor", targetNamespace = "http://tempuri.org/")
        String usuarioProveedor,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "identificador", targetNamespace = "http://tempuri.org/")
        String identificador,
        @WebParam(name = "tsBase64", targetNamespace = "http://tempuri.org/")
        String tsBase64,
        @WebParam(name = "documentoBase64", targetNamespace = "http://tempuri.org/")
        String documentoBase64);

}
