
package gs.nom.mx.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsValida", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://validanomts.doc2sign.com/wsValida.svc?wsdl")
public class WsValida
    extends Service
{

    private final static URL WSVALIDA_WSDL_LOCATION;
    private final static WebServiceException WSVALIDA_EXCEPTION;
    private final static QName WSVALIDA_QNAME = new QName("http://tempuri.org/", "wsValida");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://validanomts.doc2sign.com/wsValida.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVALIDA_WSDL_LOCATION = url;
        WSVALIDA_EXCEPTION = e;
    }

    public WsValida() {
        super(__getWsdlLocation(), WSVALIDA_QNAME);
    }

    public WsValida(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVALIDA_QNAME, features);
    }

    public WsValida(URL wsdlLocation) {
        super(wsdlLocation, WSVALIDA_QNAME);
    }

    public WsValida(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVALIDA_QNAME, features);
    }

    public WsValida(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsValida(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IwsValida
     */
    @WebEndpoint(name = "BasicHttpBinding_IwsValida")
    public IwsValida getBasicHttpBindingIwsValida() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IwsValida"), IwsValida.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IwsValida
     */
    @WebEndpoint(name = "BasicHttpBinding_IwsValida")
    public IwsValida getBasicHttpBindingIwsValida(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IwsValida"), IwsValida.class, features);
    }

    /**
     * 
     * @return
     *     returns IwsValida
     */
    @WebEndpoint(name = "BasicHttpsBinding_IwsValida")
    public IwsValida getBasicHttpsBindingIwsValida() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IwsValida"), IwsValida.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IwsValida
     */
    @WebEndpoint(name = "BasicHttpsBinding_IwsValida")
    public IwsValida getBasicHttpsBindingIwsValida(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpsBinding_IwsValida"), IwsValida.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVALIDA_EXCEPTION!= null) {
            throw WSVALIDA_EXCEPTION;
        }
        return WSVALIDA_WSDL_LOCATION;
    }
    
}
